version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_shopping
    restart: always
    environment:
      SA_PASSWORD: "S3nh@F0rt3!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sqlserver/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S sqlserver_shopping -U sa -P S3nh@F0rt3! -Q \"SELECT 1\""]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis_shopping
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_started

  shopping.api.tests:
    image: ${DOCKER_REGISTRY-}shoppingapitests
    build:
      context: .
      dockerfile: Shopping.API.Tests/Dockerfile

volumes:
  sqlserver_data:
    driver: local
  redis_data:
    driver: local